# Generated by Django 6.0.3 on 2026-03-17 22:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_remove_studentprofile_branch_issuedbook_return_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issuedbook',
            name='fine_amount',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='total_fine_due',
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='branch',
            field=models.CharField(default='CSE', max_length=50),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='FineCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_date', models.DateField(auto_now_add=True)),
                ('received_by', models.CharField(max_length=100)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.studentprofile')),
            ],
        ),
    ]
