# Generated by Django 6.0.3 on 2026-03-17 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentprofile',
            name='branch',
        ),
        migrations.AddField(
            model_name='issuedbook',
            name='return_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
