# Generated by Django 6.0.3 on 2026-03-18 09:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_remove_issuedbook_fine_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issuedbook',
            name='issue_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
